version: '3'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

    restart: on-failure
    
  web:
    build: .
    volumes:
      - .:/code
      - /var/www/sockets:/var/www/sockets # Mount the container directory containing the Unix socket for GateWay services into the host machine  idea:  container ---> host
      - /tmp:/tmp
    network_mode: "host"
    restart: always