version: '3'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /home/user/minio/data:/data  # Adjust the host directory to the correct absolute path
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    restart: on-failure
    
  web:
    build: .
    # ports:
    #   - "7000:7000"
    network_mode: "host"
    volumes:
      - .:/code
      - /tmp:/tmp
    restart: always
